name: ice
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - pillow >8.0.0,<9
  - python>3.6,<4
  - pytorch==1.10.0
  - torchvision==0.11.1
  - cudatoolkit=10.2
  - fastcore >=1.3.0,<1.4
  - fastai >=2.5.2,<2.6
  - pip
  - pip:
      - git+https://github.com/airctic/icevision.git@master#egg=icevision[all]
#  - pip:
#    - --find-links https://download.pytorch.org/whl/torch_stable.html
#
